{"id":"31365759092","type":"IssueCommentEvent","actor":{"id":57787676,"login":"baentsch","display_login":"baentsch","gravatar_id":"","url":"https://api.github.com/users/baentsch","avatar_url":"https://avatars.githubusercontent.com/u/57787676?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534","id":1866340188,"node_id":"I_kwDOA-eq3c5vPhdc","number":1534,"title":"Tests fail: cannot import name 'Config' from 'pytest'","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2023-08-25T05:46:02Z","updated_at":"2023-08-25T06:17:11Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n```\r\n[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.9/site-packages/pytest.py\", line 102, in <module>\r\n    raise SystemExit(pytest.main())\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 65, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 213, in _prepareconfig\r\n    return pluginmanager.hook.pytest_cmdline_parse(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 84, in <lambda>\r\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n    gen.send(outcome)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py\", line 94, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 80, in get_result\r\n    raise ex[1].with_traceback(ex[2])\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 789, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 997, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 943, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/local/lib/python3.9/importlib/metadata.py\", line 86, in load\r\n    module = import_module(match.group('module'))\r\n  File \"/usr/local/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py\", line 304, in load_module\r\n    exec(co, mod.__dict__)\r\n  File \"/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py\", line 6, in <module>\r\n    from pytest import Config, Parser\r\nImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)\r\nFAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests \r\ncd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nninja: build stopped: subcommand failed.\r\n*** Error code 1\r\n```\r\n\r\n**To Reproduce**\r\nRegular build and test with the ```run_tests``` target.\r\n\r\n**Environment (please complete the following information):**\r\n - OS: FreeBSD 13.2\r\n - Compiler version used clang-16\r\n - Build variables used n/a\r\n - liboqs version rev.914764c9\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/timeline","performed_via_github_app":null,"state_reason":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692824611","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534#issuecomment-1692824611","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","id":1692824611,"node_id":"IC_kwDOA-eq3c5k5nQj","user":{"login":"baentsch","id":57787676,"node_id":"MDQ6VXNlcjU3Nzg3Njc2","avatar_url":"https://avatars.githubusercontent.com/u/57787676?v=4","gravatar_id":"","url":"https://api.github.com/users/baentsch","html_url":"https://github.com/baentsch","followers_url":"https://api.github.com/users/baentsch/followers","following_url":"https://api.github.com/users/baentsch/following{/other_user}","gists_url":"https://api.github.com/users/baentsch/gists{/gist_id}","starred_url":"https://api.github.com/users/baentsch/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/baentsch/subscriptions","organizations_url":"https://api.github.com/users/baentsch/orgs","repos_url":"https://api.github.com/users/baentsch/repos","events_url":"https://api.github.com/users/baentsch/events{/privacy}","received_events_url":"https://api.github.com/users/baentsch/received_events","type":"User","site_admin":false},"created_at":"2023-08-25T06:17:11Z","updated_at":"2023-08-25T06:17:11Z","author_association":"MEMBER","body":"Is this really an OQS problem? I don't see a single line of OQS (python/test) code involved in the trace above: Can you please point to that?","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692824611/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2023-08-25T06:17:11Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31365946736","type":"IssueCommentEvent","actor":{"id":271906,"login":"yurivict","display_login":"yurivict","gravatar_id":"","url":"https://api.github.com/users/yurivict","avatar_url":"https://avatars.githubusercontent.com/u/271906?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534","id":1866340188,"node_id":"I_kwDOA-eq3c5vPhdc","number":1534,"title":"Tests fail: cannot import name 'Config' from 'pytest'","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2023-08-25T05:46:02Z","updated_at":"2023-08-25T06:27:24Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n```\r\n[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.9/site-packages/pytest.py\", line 102, in <module>\r\n    raise SystemExit(pytest.main())\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 65, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 213, in _prepareconfig\r\n    return pluginmanager.hook.pytest_cmdline_parse(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 84, in <lambda>\r\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n    gen.send(outcome)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py\", line 94, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 80, in get_result\r\n    raise ex[1].with_traceback(ex[2])\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 789, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 997, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 943, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/local/lib/python3.9/importlib/metadata.py\", line 86, in load\r\n    module = import_module(match.group('module'))\r\n  File \"/usr/local/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py\", line 304, in load_module\r\n    exec(co, mod.__dict__)\r\n  File \"/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py\", line 6, in <module>\r\n    from pytest import Config, Parser\r\nImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)\r\nFAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests \r\ncd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nninja: build stopped: subcommand failed.\r\n*** Error code 1\r\n```\r\n\r\n**To Reproduce**\r\nRegular build and test with the ```run_tests``` target.\r\n\r\n**Environment (please complete the following information):**\r\n - OS: FreeBSD 13.2\r\n - Compiler version used clang-16\r\n - Build variables used n/a\r\n - liboqs version rev.914764c9\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/timeline","performed_via_github_app":null,"state_reason":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692834429","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534#issuecomment-1692834429","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","id":1692834429,"node_id":"IC_kwDOA-eq3c5k5pp9","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"created_at":"2023-08-25T06:27:24Z","updated_at":"2023-08-25T06:27:24Z","author_association":"NONE","body":"Maybe pytest is unstable.\r\nIn my experience, pytest breaks a lot due to all sorts of problems on many projects.\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692834429/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2023-08-25T06:27:25Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31365965231","type":"IssueCommentEvent","actor":{"id":271906,"login":"yurivict","display_login":"yurivict","gravatar_id":"","url":"https://api.github.com/users/yurivict","avatar_url":"https://avatars.githubusercontent.com/u/271906?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534","id":1866340188,"node_id":"I_kwDOA-eq3c5vPhdc","number":1534,"title":"Tests fail: cannot import name 'Config' from 'pytest'","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2023-08-25T05:46:02Z","updated_at":"2023-08-25T06:28:22Z","closed_at":"2023-08-25T06:28:21Z","author_association":"NONE","active_lock_reason":null,"body":"**Describe the bug**\r\n```\r\n[  0% 1/1] cd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/usr/local/lib/python3.9/site-packages/pytest.py\", line 102, in <module>\r\n    raise SystemExit(pytest.main())\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 65, in main\r\n    config = _prepareconfig(args, plugins)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 213, in _prepareconfig\r\n    return pluginmanager.hook.pytest_cmdline_parse(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n    return self._inner_hookexec(hook, methods, kwargs)\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 84, in <lambda>\r\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n    gen.send(outcome)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/helpconfig.py\", line 94, in pytest_cmdline_parse\r\n    config = outcome.get_result()\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 80, in get_result\r\n    raise ex[1].with_traceback(ex[2])\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\r\n    res = hook_impl.function(*args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 789, in pytest_cmdline_parse\r\n    self.parse(args)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 997, in parse\r\n    self._preparse(args, addopts=addopts)\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/config/__init__.py\", line 943, in _preparse\r\n    self.pluginmanager.load_setuptools_entrypoints(\"pytest11\")\r\n  File \"/usr/local/lib/python3.9/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints\r\n    plugin = ep.load()\r\n  File \"/usr/local/lib/python3.9/importlib/metadata.py\", line 86, in load\r\n    module = import_module(match.group('module'))\r\n  File \"/usr/local/lib/python3.9/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py\", line 304, in load_module\r\n    exec(co, mod.__dict__)\r\n  File \"/usr/local/lib/python3.9/site-packages/typeguard/_pytest_plugin.py\", line 6, in <module>\r\n    from pytest import Config, Parser\r\nImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.9/site-packages/pytest.py)\r\nFAILED: tests/CMakeFiles/run_tests /usr/ports/security/liboqs/work/.build/tests/CMakeFiles/run_tests \r\ncd /usr/ports/security/liboqs/work/liboqs-0.8.0-14-g914764c9 && /usr/local/bin/cmake -E env OQS_BUILD_DIR=/usr/ports/security/liboqs/work/.build python3 -m pytest --verbose --ignore=scripts/copy_from_upstream/repos\r\nninja: build stopped: subcommand failed.\r\n*** Error code 1\r\n```\r\n\r\n**To Reproduce**\r\nRegular build and test with the ```run_tests``` target.\r\n\r\n**Environment (please complete the following information):**\r\n - OS: FreeBSD 13.2\r\n - Compiler version used clang-16\r\n - Build variables used n/a\r\n - liboqs version rev.914764c9\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534/timeline","performed_via_github_app":null,"state_reason":"not_planned"},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692835392","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1534#issuecomment-1692835392","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1534","id":1692835392,"node_id":"IC_kwDOA-eq3c5k5p5A","user":{"login":"yurivict","id":271906,"node_id":"MDQ6VXNlcjI3MTkwNg==","avatar_url":"https://avatars.githubusercontent.com/u/271906?v=4","gravatar_id":"","url":"https://api.github.com/users/yurivict","html_url":"https://github.com/yurivict","followers_url":"https://api.github.com/users/yurivict/followers","following_url":"https://api.github.com/users/yurivict/following{/other_user}","gists_url":"https://api.github.com/users/yurivict/gists{/gist_id}","starred_url":"https://api.github.com/users/yurivict/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/yurivict/subscriptions","organizations_url":"https://api.github.com/users/yurivict/orgs","repos_url":"https://api.github.com/users/yurivict/repos","events_url":"https://api.github.com/users/yurivict/events{/privacy}","received_events_url":"https://api.github.com/users/yurivict/received_events","type":"User","site_admin":false},"created_at":"2023-08-25T06:28:21Z","updated_at":"2023-08-25T06:28:21Z","author_association":"NONE","body":"Yes, it is a pytest problem.\r\n\r\nSorry for the noise!","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1692835392/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2023-08-25T06:28:22Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31377631701","type":"IssueCommentEvent","actor":{"id":23340773,"login":"ashman-p","display_login":"ashman-p","gravatar_id":"","url":"https://api.github.com/users/ashman-p","avatar_url":"https://avatars.githubusercontent.com/u/23340773?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533/events","html_url":"https://github.com/open-quantum-safe/liboqs/pull/1533","id":1865680268,"node_id":"PR_kwDOA-eq3c5YuN-3","number":1533,"title":"LMS updated to use new SK API","user":{"login":"ashman-p","id":23340773,"node_id":"MDQ6VXNlcjIzMzQwNzcz","avatar_url":"https://avatars.githubusercontent.com/u/23340773?v=4","gravatar_id":"","url":"https://api.github.com/users/ashman-p","html_url":"https://github.com/ashman-p","followers_url":"https://api.github.com/users/ashman-p/followers","following_url":"https://api.github.com/users/ashman-p/following{/other_user}","gists_url":"https://api.github.com/users/ashman-p/gists{/gist_id}","starred_url":"https://api.github.com/users/ashman-p/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ashman-p/subscriptions","organizations_url":"https://api.github.com/users/ashman-p/orgs","repos_url":"https://api.github.com/users/ashman-p/repos","events_url":"https://api.github.com/users/ashman-p/events{/privacy}","received_events_url":"https://api.github.com/users/ashman-p/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2023-08-24T18:32:10Z","updated_at":"2023-08-25T14:44:50Z","closed_at":null,"author_association":"COLLABORATOR","active_lock_reason":null,"draft":false,"pull_request":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/pulls/1533","html_url":"https://github.com/open-quantum-safe/liboqs/pull/1533","diff_url":"https://github.com/open-quantum-safe/liboqs/pull/1533.diff","patch_url":"https://github.com/open-quantum-safe/liboqs/pull/1533.patch","merged_at":null},"body":"<!-- Please give a brief explanation of the purpose of this pull request. -->\r\n\r\n<!-- Does this PR resolve any issue?  If so, please reference it using automatic-closing keywords like \"Fixes #123.\" -->\r\n\r\n<!-- Please answer the following questions to help manage version and changes across projects. -->\r\n\r\n* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)\r\n* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)\r\n\r\n<!-- Once your pull request is ready for review and passing continuous integration tests, please convert from a draft PR to a normal PR, and request a review from one of the OQS core team members. -->\r\n","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533/timeline","performed_via_github_app":null,"state_reason":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1693482615","html_url":"https://github.com/open-quantum-safe/liboqs/pull/1533#issuecomment-1693482615","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1533","id":1693482615,"node_id":"IC_kwDOA-eq3c5k8H53","user":{"login":"ashman-p","id":23340773,"node_id":"MDQ6VXNlcjIzMzQwNzcz","avatar_url":"https://avatars.githubusercontent.com/u/23340773?v=4","gravatar_id":"","url":"https://api.github.com/users/ashman-p","html_url":"https://github.com/ashman-p","followers_url":"https://api.github.com/users/ashman-p/followers","following_url":"https://api.github.com/users/ashman-p/following{/other_user}","gists_url":"https://api.github.com/users/ashman-p/gists{/gist_id}","starred_url":"https://api.github.com/users/ashman-p/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ashman-p/subscriptions","organizations_url":"https://api.github.com/users/ashman-p/orgs","repos_url":"https://api.github.com/users/ashman-p/repos","events_url":"https://api.github.com/users/ashman-p/events{/privacy}","received_events_url":"https://api.github.com/users/ashman-p/received_events","type":"User","site_admin":false},"created_at":"2023-08-25T14:44:50Z","updated_at":"2023-08-25T14:44:50Z","author_association":"COLLABORATOR","body":"Looks like variant XMSS-SHAKE_20_256 is hanging. This should be addressed after things settle with all the API changes.","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1693482615/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2023-08-25T14:44:51Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"31381515271","type":"IssueCommentEvent","actor":{"id":5332385,"login":"jamuir","display_login":"jamuir","gravatar_id":"","url":"https://api.github.com/users/jamuir","avatar_url":"https://avatars.githubusercontent.com/u/5332385?"},"repo":{"id":65514205,"name":"open-quantum-safe/liboqs","url":"https://api.github.com/repos/open-quantum-safe/liboqs"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393/events","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1393","id":1588848056,"node_id":"I_kwDOA-eq3c5es-W4","number":1393,"title":"Repeated OQS API calls crash on armhf/32bit","user":{"login":"baentsch","id":57787676,"node_id":"MDQ6VXNlcjU3Nzg3Njc2","avatar_url":"https://avatars.githubusercontent.com/u/57787676?v=4","gravatar_id":"","url":"https://api.github.com/users/baentsch","html_url":"https://github.com/baentsch","followers_url":"https://api.github.com/users/baentsch/followers","following_url":"https://api.github.com/users/baentsch/following{/other_user}","gists_url":"https://api.github.com/users/baentsch/gists{/gist_id}","starred_url":"https://api.github.com/users/baentsch/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/baentsch/subscriptions","organizations_url":"https://api.github.com/users/baentsch/orgs","repos_url":"https://api.github.com/users/baentsch/repos","events_url":"https://api.github.com/users/baentsch/events{/privacy}","received_events_url":"https://api.github.com/users/baentsch/received_events","type":"User","site_admin":false},"labels":[{"id":1168141259,"node_id":"MDU6TGFiZWwxMTY4MTQxMjU5","url":"https://api.github.com/repos/open-quantum-safe/liboqs/labels/help%20wanted","name":"help wanted","color":"008672","default":true,"description":"Asking for support from non-core team"},{"id":5700733396,"node_id":"LA_kwDOA-eq3c8AAAABU8pJ1A","url":"https://api.github.com/repos/open-quantum-safe/liboqs/labels/platform-specific","name":"platform-specific","color":"C4AA6F","default":false,"description":"Issue related to a specific platform configuration; core team may not have required platform"}],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2023-02-17T06:58:45Z","updated_at":"2023-08-25T17:40:48Z","closed_at":null,"author_association":"MEMBER","active_lock_reason":null,"body":"As is visible for example [here](https://github.com/open-quantum-safe/liboqs/actions/runs/4194024112/jobs/7271697077) the [speed_kem](https://github.com/open-quantum-safe/liboqs/blob/main/tests/speed_kem.c) and [speed_sig](https://github.com/open-quantum-safe/liboqs/blob/main/tests/speed_sig.c) test programs are failing for all algorithms with \"Illegal Instruction\" when running on armhf (emulated at least -- real HW not at hand).","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393/timeline","performed_via_github_app":null,"state_reason":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1693720285","html_url":"https://github.com/open-quantum-safe/liboqs/issues/1393#issuecomment-1693720285","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/1393","id":1693720285,"node_id":"IC_kwDOA-eq3c5k9B7d","user":{"login":"jamuir","id":5332385,"node_id":"MDQ6VXNlcjUzMzIzODU=","avatar_url":"https://avatars.githubusercontent.com/u/5332385?v=4","gravatar_id":"","url":"https://api.github.com/users/jamuir","html_url":"https://github.com/jamuir","followers_url":"https://api.github.com/users/jamuir/followers","following_url":"https://api.github.com/users/jamuir/following{/other_user}","gists_url":"https://api.github.com/users/jamuir/gists{/gist_id}","starred_url":"https://api.github.com/users/jamuir/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jamuir/subscriptions","organizations_url":"https://api.github.com/users/jamuir/orgs","repos_url":"https://api.github.com/users/jamuir/repos","events_url":"https://api.github.com/users/jamuir/events{/privacy}","received_events_url":"https://api.github.com/users/jamuir/received_events","type":"User","site_admin":false},"created_at":"2023-08-25T17:40:47Z","updated_at":"2023-08-25T17:40:47Z","author_association":"NONE","body":"@baentsch :  unfortunately, the logs for the test run you linked to have expired and are no longer visible.\r\n\r\nI took a look at a few of the recent test runs that failed on armhf but I did not see an \"Illegal Instruction\" failure.\r\n\r\nCan you provide an updated pointer?","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs/issues/comments/1693720285/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2023-08-25T17:40:48Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
